meta_product_name: "EasyBlood"
meta_title: "EasyBlood | Porque doar é fácil"
meta_description: "Quanto mais cadastros, maiores as chances de uma campanha de doação de sangue perto de você"
meta_image: "http://res.cloudinary.com/mscorzoni/image/upload/cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@socialeasyblood"   # required for Twitter Cards
